[package]
name = "speed_crawler_rust"
version = "0.1.0"
edition = "2024"

[dependencies]
godot = "0.4.5"
rand = "0.9.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "2.0.18"

[lib]
crate-type = ["cdylib"]
